services:
  delok:
    image: ghcr.io/hilmoo/delok:latest
    container_name: delok
    command: sleep infinity
    environment:
      - VITE_ISPROD=true
      - VITE_ELEMES_URL=${VITE_ELEMES_URL}
      - ELEMES_URL_DOCKER=${ELEMES_URL_DOCKER}
      - NODE_RPC_URL=${NODE_RPC_URL}
      - VITE_NODE_RPC_URL=${VITE_NODE_RPC_URL}
    networks:
      - delok_elemes-app

  oracle:
    image: ghcr.io/hilmoo/delok-oracle:latest
    container_name: delok_oracle
    environment:
      - ELEMES_URL_DOCKER=${ELEMES_URL_DOCKER}
      - KUBO_RPC_DOCKER=${KUBO_RPC_DOCKER}
      - NODE_RPC_URL=${NODE_RPC_URL}
      - ORACLE_PRIVATE_KEY=${ORACLE_PRIVATE_KEY}
    networks:
      - delok_elemes-oracle
      - delok_kubo-oracle

  hardhat:
    image: ghcr.io/hilmoo/hadhat-docker-node:main
    container_name: delok_hardhat
    ports:
      - "8545:8545"

  kubo:
    image: ipfs/kubo:v0.35.0
    container_name: delok_ipfs_host
    volumes:
      - delok_ipfs_staging:/export
      - delok_ipfs_data:/data/ipfs
    ports:
      - 4001:4001
      - 4001:4001/udp
      - 127.0.0.1:8080:8080
      - 127.0.0.1:5001:5001
    networks:
      - delok_kubo-oracle

  LMS_elemes:
    image: ghcr.io/hilmoo/elemes:1.2.0
    container_name: delok_elemes
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
    depends_on:
      db_elemes:
        condition: service_healthy
    networks:
      - delok_elemes-network
      - delok_elemes-oracle
      - delok_elemes-app

  db_elemes:
    image: postgres:17-alpine
    container_name: delok_elemes-db
    volumes:
      - delok_db-elemes:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - delok_elemes-network

volumes:
  delok_db-elemes:
  delok_ipfs_staging:
  delok_ipfs_data:

networks:
  delok_elemes-app:
  delok_elemes-network:
  delok_elemes-oracle:
  delok_kubo-oracle:
