services:
  delok:
    image: ghcr.io/hilmoo/delok:1.1.3
    container_name: delok
    environment:
      - VITE_ISPROD=true
      - VITE_ELEMES_URL=${VITE_ELEMES_URL}
      - ELEMES_URL_DOCKER=${ELEMES_URL_DOCKER}
      - NODE_RPC_URL=${NODE_RPC_URL}
      - VITE_NODE_RPC_URL=${VITE_NODE_RPC_URL}
      - VITE_COOKIE_DOMAIN=${VITE_COOKIE_DOMAIN}
      - VITE_BASE_URL=${VITE_BASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}

  oracle:
    image: ghcr.io/hilmoo/delokoracle:1.1.0
    container_name: delok_oracle
    environment:
      - ELEMES_URL_DOCKER=${ELEMES_URL_DOCKER}
      - KUBO_RPC_DOCKER=${KUBO_RPC_DOCKER}
      - NODE_RPC_URL=${NODE_RPC_URL}
      - ORACLE_PRIVATE_KEY=${ORACLE_PRIVATE_KEY}
      - ORACLE_HEADER=${ORACLE_HEADER}
    networks:
      - delok_kubo-oracle

  kubo:
    image: ipfs/kubo:v0.35.0
    container_name: delok_ipfs_host
    volumes:
      - delok_ipfs_staging:/export
      - delok_ipfs_data:/data/ipfs
    ports:
      - 4001:4001
      - 4001:4001/udp
      - 127.0.0.1:8080:8080
      - 127.0.0.1:5001:5001
    networks:
      - delok_kubo-oracle

volumes:
  delok_ipfs_staging:
  delok_ipfs_data:

networks:
  delok_kubo-oracle:
