services:
  LMS_elemes:
    image: ghcr.io/hilmoo/elemes:1.1.1
    container_name: delok_elemes
    ports:
      - "4000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
    depends_on:
      db_elemes:
        condition: service_healthy
    networks:
      - delok_elemes-network

  db_elemes:
    image: postgres:17-alpine
    container_name: delok_elemes-db
    volumes:
      - delok_db-elemes:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - delok_elemes-network

volumes:
  delok_db-elemes:

networks:
  delok_elemes-network:
