services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    env_file:
      - .env

  hardhat:
    build:
      context: ./hardhat
      dockerfile: Dockerfile
    network_mode: service:app

  block-explorer:
    image: ghcr.io/hilmoo/custom-block-explorer:main
    container_name: block-explorer
    network_mode: service:app
